List searchCategories = [
  "Trending",
  "Hacks",
  "Decor",
  "Food",
  "Dog",
  "Travel",
  "Art"
];

List searchImages = [
  "assets/post/ammachamberlain_post.jpg",
  "assets/post/arianagrande_post.jpg",
  "assets/post/italy_post.jpg",
  "assets/post/ballet_post.jpg",
  "assets/post/billieeilish_post.jpg",
  "assets/post/corbynbesson_post.jpg",
  "assets/post/germany_post.jpg",
  "assets/post/corndogs_post.jpg",
  "assets/post/doggie_post.jpg",
  "assets/post/japan_post.jpg",
  "assets/post/johnnyorlando_post.jpg",
  "assets/post/justinbieber_post.jpg",
  "assets/post/dubai_post.jpg",
  "assets/post/lillyk_post.jpg",
  "assets/post/oliviarodrigo_post.jpg",
  "assets/post/pointe_post.jpg",
  "assets/post/portugal_post.jpg",
  "assets/post/sabrinacarpenter_post.jpg",
  "assets/post/scotland_post.jpg",
  "assets/post/seaveydaniel_post.jpg",
  "assets/post/shawnmendes_post.jpg",
  "assets/post/greece_post.jpg",
  "assets/post/sofiedossi_post.jpg",
  "assets/post/taylorswift_post.jpg",
  "assets/post/zendaya_post.jpg",
];